# Generated by Django 4.2.23 on 2026-07-19 17:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import django_summernote.fields
import member.models
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arrondissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('auteur', models.CharField(default='Équipe Connect Jeunes', max_length=150)),
                ('description_courte', models.TextField(help_text="Résumé de l'article")),
                ('contenu', django_summernote.fields.SummernoteTextField(verbose_name="Contenu de l'article (Summernote)")),
                ('image_principale', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('date_publication', models.DateTimeField(default=django.utils.timezone.now)),
                ('actif', models.BooleanField(default=True)),
                ('meta_title', models.CharField(blank=True, help_text='Titre SEO', max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, help_text='Description SEO', null=True)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='BadgeMembre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Nom complet')),
                ('telephone', models.CharField(db_index=True, max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Format de téléphone invalide', regex='^\\+?[0-9\\s\\-\\(\\)]{8,20}$')], verbose_name='Numéro de téléphone')),
                ('adresse', models.TextField(verbose_name='Adresse')),
                ('barcode_id', models.CharField(max_length=100, unique=True, verbose_name='ID Code-barres')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_confirmation', models.DateTimeField(auto_now=True, verbose_name='Date de confirmation')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('confirme', 'Confirmé'), ('telecharge', 'Téléchargé')], default='brouillon', max_length=20, verbose_name='Statut')),
                ('telechargements_png', models.PositiveIntegerField(default=0, verbose_name='Téléchargements PNG')),
                ('telechargements_pdf', models.PositiveIntegerField(default=0, verbose_name='Téléchargements PDF')),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Badge Membre',
                'verbose_name_plural': 'Badges Membres',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse email')),
                ('sujet', models.CharField(max_length=255, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('traite', models.BooleanField(default=False, verbose_name='Message traité')),
            ],
            options={
                'verbose_name': 'Message de Contact',
                'verbose_name_plural': 'Messages de Contact',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(default='BJ', max_length=2)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('categorie', models.CharField(choices=[('solidarite', 'Solidarité'), ('exploration', 'Exploration'), ('inclusion', 'Inclusion'), ('orientation', 'Orientation'), ('autre', 'Autre')], default='orientation', max_length=50)),
                ('date_debut', models.DateField()),
                ('heure_debut', models.TimeField(blank=True, null=True)),
                ('heure_fin', models.TimeField(blank=True, null=True)),
                ('lieu', models.CharField(default='Savè, Bénin', max_length=255)),
                ('image_principale', models.ImageField(blank=True, null=True, upload_to='evenements/')),
                ('description_courte', models.TextField(help_text="Résumé rapide s'affichant sur les cartes de listing")),
                ('contenu', django_summernote.fields.SummernoteTextField(verbose_name="Contenu de l'événement (Summernote)")),
                ('est_a_ne_pas_manquer', models.BooleanField(default=False, verbose_name='À la une / À ne pas manquer')),
                ('actif', models.BooleanField(default=True)),
                ('meta_title', models.CharField(blank=True, help_text='Titre SEO', max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, help_text='Description SEO', null=True)),
            ],
            options={
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='GalerieMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('categorie', models.CharField(choices=[('orientation', 'Orientation'), ('formation', 'Formation'), ('solidarite', 'Solidarité'), ('exploration', 'Exploration'), ('inclusion', 'Inclusion'), ('autre', 'Autre')], default='orientation', max_length=50)),
                ('image', models.ImageField(upload_to='galerie/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Média de la Galerie',
                'verbose_name_plural': 'Médias de la Galerie',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse email')),
                ('nom', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nom complet')),
                ('consent_marketing', models.BooleanField(default=True, verbose_name='Accepte de recevoir des emails')),
                ('consent_data_processing', models.BooleanField(default=True, verbose_name='Accepte le traitement des données')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('subscribed', 'Abonné'), ('unsubscribed', 'Désinscrit')], default='subscribed', max_length=20)),
                ('date_subscription', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Abonnement Newsletter',
                'verbose_name_plural': 'Abonnements Newsletter',
            },
        ),
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entite', models.CharField(max_length=255, verbose_name="Nom de l'Entité/Organisation")),
                ('sigle', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sigle / Acronyme')),
                ('type_entite', models.CharField(choices=[('ONG', 'ONG'), ('Association', 'Association de Jeunesse'), ('Mouvement', 'Mouvement Partenaire (ex: MMT)'), ('Institution', 'Institution / Organisation Publique'), ('Privé', 'Secteur Privé')], default='Association', max_length=50, verbose_name='Type de Partenaire')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partenaires_logos/', validators=[member.models.validate_file_size], verbose_name='Logo ou Image du Partenaire')),
                ('nom_contact_principal', models.CharField(max_length=100, verbose_name='Nom du Contact Principal')),
                ('fonction_contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fonction du Contact')),
                ('email_contact', models.EmailField(max_length=100, unique=True, verbose_name='Email (Principal)')),
                ('telephone_contact', models.CharField(blank=True, max_length=50, null=True, verbose_name='Téléphone')),
                ('domaine_action', models.CharField(help_text='Ex: Artisanat, Citoyenneté, Environnement...', max_length=255, verbose_name="Domaine d'Action Principal")),
                ('zone_geographique', models.CharField(max_length=255, verbose_name="Zone Géographique d'Opération (Ex: Ouémé)")),
                ('nombre_membres', models.IntegerField(blank=True, null=True, verbose_name='Nombre de Membres / Bénéficiaires')),
                ('date_debut_partenariat', models.DateField(verbose_name='Date de Début du Partenariat')),
                ('statut_partenariat', models.CharField(choices=[('Actif', 'Actif'), ('Veille', 'En Veille / Latent'), ('Terminé', 'Terminé'), ('Nego', 'En Négociation')], default='Veille', max_length=50, verbose_name='Statut Actuel du Partenariat')),
                ('meta_title', models.CharField(blank=True, help_text='Titre SEO', max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, help_text='Description SEO', null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('objectifs_collaboration', models.TextField(help_text='Description détaillée de la synergie et des buts communs.', verbose_name='Objectifs de la Collaboration')),
                ('notes_suivi', models.TextField(blank=True, null=True, verbose_name='Notes de Suivi et Historique')),
            ],
            options={
                'verbose_name': 'Partenaire et Collaboration',
                'verbose_name_plural': 'Partenaires et Collaborations',
                'ordering': ['nom_entite'],
            },
        ),
        migrations.CreateModel(
            name='Pilier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre du pilier')),
                ('icone', models.CharField(default='school', help_text="Nom de l'icône Material Symbols Outlined (ex: school, diversity_3, payments, hub, science)", max_length=100)),
                ('description', django_summernote.fields.SummernoteTextField(verbose_name='Description')),
                ('ordre', models.IntegerField(default=1, verbose_name="Ordre d'affichage")),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': "Pilier d'Action",
                'verbose_name_plural': "Piliers d'Action",
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('statut', models.CharField(choices=[('avenir', 'À venir'), ('encours', 'En cours'), ('realise', 'Réalisé')], default='realise', max_length=20)),
                ('lieu', models.CharField(default='Savè, Bénin', max_length=255)),
                ('description', django_summernote.fields.SummernoteTextField(verbose_name='Description détaillée')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projets/')),
                ('avancement', models.PositiveIntegerField(default=100, help_text="Pourcentage d'avancement (0 à 100)")),
                ('avancement_label', models.CharField(default='100% Réalisé', help_text='Ex: 100+ jeunes formés', max_length=100)),
                ('layout_large', models.BooleanField(default=False, help_text='Cochez pour afficher cette carte en format large (span 8 colonnes) au lieu de normal (span 4 colonnes)')),
                ('actif', models.BooleanField(default=True)),
                ('meta_title', models.CharField(blank=True, help_text='Titre SEO', max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, help_text='Description SEO', null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Temoignage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auteur', models.CharField(max_length=100, verbose_name="Nom de l'auteur")),
                ('fonction', models.CharField(blank=True, max_length=100, verbose_name='Fonction/Métier')),
                ('ville', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('citation', models.TextField(verbose_name='Témoignage / Citation')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='temoignages/', verbose_name='Photo')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Afficher ce témoignage')),
                ('ordre', models.IntegerField(default=1, verbose_name="Ordre d'affichage")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Témoignage',
                'verbose_name_plural': 'Témoignages',
                'ordering': ['ordre', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('arrondissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighborhoods', to='member.arrondissement')),
            ],
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communes', to='member.department')),
            ],
        ),
        migrations.AddField(
            model_name='arrondissement',
            name='commune',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrondissements', to='member.commune'),
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civility', models.CharField(choices=[('Homme', 'Monsieur'), ('Femme', 'Madame')], max_length=10)),
                ('last_name', models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='Ce champ ne peut contenir que des lettres, espaces ou tirets.', regex="^[A-Za-zÀ-ÖØ-öø-ÿ \\'-]+$")])),
                ('first_name', models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='Ce champ ne peut contenir que des lettres, espaces ou tirets.', regex="^[A-Za-zÀ-ÖØ-öø-ÿ \\'-]+$")])),
                ('email', models.EmailField(blank=True, error_messages={'unique': 'Cet email est déjà utilisé.'}, max_length=254, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Numéro de téléphone (format international conseillé, ex: +22990000000)', max_length=128, null=True, region='BJ')),
                ('birth_date', models.DateField()),
                ('profession', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('country', django_countries.fields.CountryField(default='BJ', max_length=2)),
                ('influence_zone', models.CharField(blank=True, max_length=100, null=True)),
                ('nip', models.CharField(error_messages={'unique': 'Ce NIP existe déjà dans la base des adhérents.'}, max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]+$', 'Le NIP doit contenir uniquement des chiffres.')])),
                ('id_document', models.FileField(blank=True, null=True, upload_to='members/id_documents/', validators=[member.models.validate_file_size])),
                ('consent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('arrondissement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.arrondissement')),
                ('commune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.commune')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.department')),
                ('neighborhood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.neighborhood')),
                ('recommende_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members_recommended', to='member.partenaire', verbose_name='Qui vous a affilié ou parlé de Connect Jeunes ?')),
            ],
            options={
                'verbose_name': 'Membre',
                'verbose_name_plural': 'Membres',
                'ordering': ['last_name', 'first_name'],
                'unique_together': {('last_name', 'first_name', 'phone')},
            },
        ),
    ]
