name: Deploy to VPS via SSH

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p /var/www/customer/connect-jeunes
            cd /var/www/customer/connect-jeunes
            if [ ! -d ".git" ]; then
              git init
              git remote add origin https://github.com/wenjus26/connect-jeunes.git
              git fetch
              git checkout -f main
            else
              git pull origin main
            fi
            docker compose up -d --build
            docker compose exec -T web python manage.py migrate
            docker compose exec -T web python manage.py collectstatic --noinput
            docker compose exec -T web python manage.py load_benin_locations
